Fix tsc error from different casing in import and filename
src/features/auth/AuthMiddleware.ts:7:8 - error TS1261: Already included file name 'server/src/infrastructure/JWT.ts' differs from file name 'server/src/infrastructure/Jwt.ts' only in casing.
  The file is in the program because:
    Imported via '../../infrastructure/JWT' from file 'server/src/features/auth/AuthMiddleware.ts'
    Imported via '../../infrastructure/JWT' from file 'server/src/features/auth/LoginService.ts'
    Imported via '../../infrastructure/JWT' from file 'server/src/features/auth/AuthRouter.ts'
    Matched by include pattern '**/*' in 'server/tsconfig.json'